### ISSUE TITLE
SubHeader's Icon size can not be controlled

### ISSUE THREAD

**Issue by mehmetsefabalik** [Trendyol/quarkify#167]
SubHeader's left and right icon sizes should be controllable by the props of SubHeader

**Comment by yavuzkoca** [comment]
Maybe it would be better to take as component in props:

```
<SubHeader leftIcon={<Icon name="back-button" color="red"/>} title="Some Title"/>
```

instead of

```
<SubHeader leftIconName="back-button" leftIconColor="red" title="Some Title"/>
```


In that way, users can give any props they want to pass into child components of the components such as SubHeader.
