### ISSUE TITLE
Search Modal should be implemented

### ISSUE THREAD

**Issue by yavuzalpty** [Trendyol/quarkify#180]

**Comment by yavuzkoca** [comment]
Can you give more detail about this modal?

**Comment by yavuzalpty** [comment]
Not only I can give details, but also I can draw the picture of clarity, Abidin. 

<img width="905" alt="Screen Shot 2019-11-16 at 17 27 46" src="https://user-images.githubusercontent.com/56351258/68994671-b7ccf280-0896-11ea-96d6-902d44c8c1a9.png">

**Comment by yavuzkoca** [comment]
This search modal is not something necessary to build. It has an input field at top and some list items below of it. Its quite custom modal to be one of the Quarkify's components.
